# -*- coding: utf-8 -*-
"""Working_with_Images.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_BFp6eQRljC3mPRZuD_BdmdAks0zFG-
"""

from PIL import Image

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
uploaded = files.upload()

mac = Image.open('example.jpg')

display(mac)

mac.size

mac.format_description

mac.crop((10,10,200,200))

mac

halfway = 6016/2

x = halfway - 650
w = halfway + 450
y = 1000
h = 2050

mac.crop((x,y,w,h))

img = mac.crop((x,y,w,h))

mac.paste(img, (10,10))

mac

